import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import StaticNavbar from "@/app/components/staticNavbar";

const jost = Jost({subsets: ['latin'], weight:["100","200","300","400","500","600","700","800","900"]})

export const metadata: Metadata = {
  title: "NRam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Toaster />
        <StaticNavbar />
        {children}
      </body>
    </html>
  );
}
